namespace Noxrat.Analyzers;

public enum EDiagnosticId
{
    NAMESPACE_DOES_NOT_MATCH_RULE = 0,
    REQUIRE_ATTRIBUTE_DOESNT_CONTAIN_ATTRIBUTE,
    FIELD_IS_NOT_CONST,
    FIELD_IS_NOT_A_STRING,
    BAKE_STRING_CONSTANT_CLASS_MUST_BE_PARTIAL,
    BAKE_STRING_CONSTANT_FIELD_LIST_EMPTY,
    BAKE_STRING_CONSTANT_VARIABLE_NAME_INVALID,
    BAKE_STRING_CONSTANT_VARIABLE_NAME_COLLISION,
    BAKE_STRING_CONSTANT_NESTED_CLASS_NOT_SUPPORTED,
    BAKE_STRING_CONSTANT_FIELD_REFERENCE_INVALID,
    BAKE_STRING_CONSTANT_FORMAT_INVALID,
    COUNT,
}
